describe('with', function()
  it('returns the observable it is called on if no other sources are specified', function()
    local observable = Rx.Observable.fromRange(1, 5):with()
    expect(observable).to.produce(1, 2, 3, 4, 5)
  end)

  it('should produce the most recent values when any observable produces a value', function()
    local subjectA = Rx.Subject.create()
    local subjectB = Rx.Subject.create()
    local onNext = spy()
    local observable = subjectA:with(subjectB):subscribe(Rx.Observer.create(onNext))
    subjectA:onNext('a')
    subjectA:onNext('b')
    subjectB:onNext('c')
    subjectB:onNext('d')
    subjectA:onNext('e')
    subjectA:onNext('f')
    expect(onNext).to.equal({{'a', nil}, {'b', nil}, {'b', 'c'}, {'b', 'd'}, {'e', 'd'}, {'f', 'd'}})
  end)

  it('should complete only when all observables complete', function()
    local subjectA = Rx.Subject.create()
    local subjectB = Rx.Subject.create()
    local onCompleted = spy()
    subjectA:with(subjectB):subscribe(Rx.Observer.create(_, _, onCompleted))
    subjectA:onNext('a')
    subjectA:onNext('b')
    subjectA:onCompleted()
    expect(#onCompleted).to.equal(0)
    subjectB:onNext('c')
    subjectB:onNext('d')
    subjectB:onCompleted()
    expect(#onCompleted).to.equal(1)
  end)

  it('should unsubscribe from all source observables', function()
    local unsubscribeA = spy()
    local observableA = Rx.Observable.create(function(observer)
      return Rx.Subscription.create(unsubscribeA)
    end)

    local unsubscribeB = spy()
    local observableB = Rx.Observable.create(function(observer)
      return Rx.Subscription.create(unsubscribeB)
    end)

    local subscription = observableA:with(observableB):subscribe()
    subscription:unsubscribe()
    expect(#unsubscribeA).to.equal(1)
    expect(#unsubscribeB).to.equal(1)
  end)
end)
